[DATA]
DISABLE_LIGHTSINI=0

[BASIC]
IS_LOW_BEAM_AVAILABLE =1

[LIGHTING]
EMISSIVE_BRAKELIGHTS_MULT = 4.0
EMISSIVE_HEADLIGHTS_MULT=1.4
EMISSIVE_PARKINGLIGHTS_MULT = 2.5
EMISSIVE_MULT=1
INTERIOR_DARKEN_LIGHT=1.0
INTERIOR_DARKEN_SPECULAR=0.5
INTERIOR_FAKE_SHADOW_OPACITY=0.5
INTERIOR_FAKE_UPPER_SHADOW_FADE=0.1
INTERIOR_FAKE_UPPER_SHADOW_HEIGHT=-0.1
LIT_MULTIPLIER=0.5
SPECULAR_MULTIPLIER=1
[LIGHT_HEADLIGHT_0]
RANGE=150
[EMISSIVE_REVERSE_0] 
NAME=taillightR_reverse_light_lod0
COLOR=100,100,100,10
LAG=0.1
SIMULATE_HEATING=3

[INCLUDE: common/materials_interior.ini]

[Material_Aluminium_v2]   
Materials = chrome_1
Metalness=0.25
Smoothness = 0.9
Reflectance = 1.5
CubemapReflectionBlur = 0.8
DetailTexture = 1
DetailNormalTexture = common/pbr_metal.dds
DetailNormalPBRSecondaryColor = 0, 0, 0, 0
DetailScale = 30
DetailNormalBlend = 1
DetailNormalPBRSmoothnessGamma = 30

-----------------------------------------

[INCLUDE: common/navigators.ini]

[Navigator_StyleSimpleLight]
Meshes = LCD_002
Resolution = 1110, 419
Offset = 0, 0
Size = 1110, 405

[LIGHTING]
EMISSIVE_HEADLIGHTS_MULT=1

[BOUNCED_HEADLIGHTS]
ACTIVE=1
FADE_AT=200
FADE_SMOOTH=50
FALLOFF=0.7
GRADIENT_OFFSET=0.8
MULT=1, 1, 1, 1
OFFSET=7

[LIGHT_HEADLIGHT_0]
AFFECTS_TRACK=1
BOUND_EMISSIVE_MAX=500
BOUND_EXP=1
COLOR=0.957143, 0.957143, 1, 10
DIFFUSE_CONCENTRATION=0.88
DIRECTION=0, -0.2, 1
EXTERIOR_ONLY=0
FADE_AT=450
FADE_SMOOTH=50
INTERIOR_ONLY=0
LOWBEAM_RANGE_MAX=30
LOWBEAM_RANGE_MULT=0.8
LOWBEAM_RANGE_ONCOMING_MULT=0.4
MIRROR=0.624442
MIRROR_DIRECTION=0
POPUP_ENABLED=0
POSITION=0, 0.64, 2.2
RANGE=110
RANGE_GRADIENT_OFFSET=0
SECOND_SPOT=129.6
SECOND_SPOT_INTENSITY=0.27
SECOND_SPOT_RANGE=20
SECOND_SPOT_SHARPNESS=0.58
SECOND_SPOT_SKIP=0.3
SINGLE_FREQUENCY=0
SPECULAR_MULT=1
SPOT=48
SPOT_EDGE=0.02088, 0.01992, 0.018
SPOT_EDGE_SHARPNESS=50
SPOT_SHARPNESS=0
SPOT_UP=0.0499376, 0.998752, 0

[EMISSIVE_EXTRA_A_0]
BIND_TO_EXTRA_A=1
BIND_TO_HEADLIGHTS=0
NAME=headlightR_textured_reflector
COLOR=40,40,45, 3
LAG=0.2
SIMULATE_HEATING=0.3

[EMISSIVE_EXTRA_A_1]
BIND_TO_EXTRA_A=1
BIND_TO_HEADLIGHTS=0
NAME=headlightL_textured_reflector
COLOR=40,40,45, 3
LAG=0.2
SIMULATE_HEATING=0.3

[INCLUDE: common/custom_emissive.ini]
DashHighlightColor = 1.4, 0.8, 0.8
HeatingMult = 0.5

[EMISSIVE_BRAKE_0]
NAME=Rear_Brakes
COLOR=450,1.5,1,1
LAG=0.7
SIMULATE_HEATING=0
LOCATION=REAR

[LIGHT_BRAKE_0] ; For Track not Car
AFFECTS_TRACK=1
COLOR=1, 0, 0, 1.5
DIFFUSE_CONCENTRATION=0.88
DIRECTION=0, 0, -1
EXTERIOR_ONLY=0
FADE_AT=120
FADE_SMOOTH=30
INTERIOR_ONLY=0
MIRROR=0.468203
OFF_COLOR=1, 0.0911936, 0.0265662, 1.05
OFF_FADE_MULT=1.674586
OFF_MIRROR=0.549986
OFF_MULT=0.1
OFF_POSITION=0, 0.54357, -2.56
OFF_RANGE_MULT=0.767561
POSITION=0, 0.547034, -2.2
RANGE=3
RANGE_GRADIENT_OFFSET=0.3
SPECULAR_MULT=0.5
SPOT=135.5
SPOT_EDGE=0.582, 0.582, 0.582
SPOT_EDGE_SHARPNESS=10
SPOT_SHARPNESS=0.3475

[LIGHT_LICENSEPLATE]
; no need to specify meshes names if material is using
; Plate_D.dds and Plate_NM.dds textures
MESHES=plate_r
OFFSET=-0.150, 0.250, -0.240
RANGE=0.6
RANGE_GRADIENT_OFFSET=0.4
SPOT=100
SPOT_SHARPNESS=0.2
COLOR=1,1,1,5.0
FALLBACK_EMISSIVE=1,1,1,2
; other supported values: TWO_ON_TOP, ONE_ON_TOP, TWO_ON_BOTTOM, ONE_ON_BOTTOM
LAYOUT=TWO_ON_TOP

[EMISSIVE_TURNSIGNAL_LEFT_0]
NAME=Rear_Left_Indicator_Glass
COLOR=200, 50, 0
LAG=0.2
SIMULATE_HEATING=0.3
LOCATION=REAR

[EMISSIVE_TURNSIGNAL_LEFT_1]
NAME=headlightL_bulb
COLOR=200,28,1
LAG=0.2
SIMULATE_HEATING=0.3
LOCATION=FRONT

[EMISSIVE_TURNSIGNAL_LEFT_4]
NAME=headlightL_glass
COLOR=200,28,1
LAG=0.2
SIMULATE_HEATING=0.3
LOCATION=FRONT

[EMISSIVE_TURNSIGNAL_LEFT_2]
NAME=mirrorL_textured_reflector
COLOR=20,7,0, 5
LAG=0.2
SIMULATE_HEATING=0.3
LOCATION=LEFT

[EMISSIVE_TURNSIGNAL_LEFT_3]
NAME=Warning_L
TOGGLE_VISIBILITY = 1
COLOR=2,20,2, 1
LAG=0.2
SIMULATE_HEATING=0
LOCATION=NONE
CAST_LIGHT=0
CLUSTER_THRESHOLD=0

[EMISSIVE_TURNSIGNAL_RIGHT_0]
NAME=Rear_Right_Indicator_Glass
COLOR=200,50, 0
LAG=0.2
SIMULATE_HEATING=0.9
LOCATION=REAR

[EMISSIVE_TURNSIGNAL_RIGHT_1]
NAME=headlightR_bulb
COLOR=200,28,1
LAG=0.2
SIMULATE_HEATING=0.3
LOCATION=FRONT

[EMISSIVE_TURNSIGNAL_RIGHT_4]
NAME=headlightR_glass
COLOR=200,28,1
LAG=0.2
SIMULATE_HEATING=0.3
LOCATION=FRONT

[EMISSIVE_TURNSIGNAL_RIGHT_2]
NAME=mirrorR_textured_reflector
COLOR=20,7,0, 5
LAG=0.2
SIMULATE_HEATING=0.3
LOCATION=RIGHT

[EMISSIVE_TURNSIGNAL_RIGHT_3]
NAME=Warning_R
TOGGLE_VISIBILITY = 1
COLOR=2,20,2, 1
LAG=0.2
SIMULATE_HEATING=0
LOCATION=NONE
CAST_LIGHT=0
CLUSTER_THRESHOLD=0

[EMISSIVE_HANDBRAKE_0]
NAME=Warning_Handbrake
TOGGLE_VISIBILITY = 1
COLOR=40,4,4,1
LAG=0.2
Warning_light

[EMISSIVE_TRACTIONCONTROL_0]
NAME=Warning_TC_OFF
TOGGLE_VISIBILITY = 1
COLOR=0
OFF_COLOR=40,20,4,1
LAG=0.2

[EMISSIVE_TRACTIONCONTROL_INACTION_0]
COLOR=40,20,4,1
NAME=Warning_TC
TOGGLE_VISIBILITY = 1
LAG=0.2

[EMISSIVE_Flash_Light]
NAME=Headlights02
COLOR=300,300,300
FLASH=1

[EMISSIVE_...]
NAME=Warning_st_wheel
TOGGLE_VISIBILITY = 1
COLOR=40,20,4,1
BIND_TO=SUSP_DAMAGE
THRESHOLD=10
LAG=0.2

[EMISSIVE_...]
NAME=Warning_Engine
TOGGLE_VISIBILITY = 1
COLOR=40,20,4,1
INPUT=ENGINE_LIFE
INPUT_THRESHOLD = 700
INPUT_THRESHOLD_INVERSE = 1
LAG=0.2

[EMISSIVE_...]
NAME=Warning_Tires_press
TOGGLE_VISIBILITY = 1
COLOR=40,20,4,1
INPUT=TYRE_PRESSURE
INPUT_THRESHOLD = 38
INPUT_SELECTOR=MAX
INPUT_SELECTOR_PIVOT=5
LAG=0.2

[EMISSIVE_LIGHT_2]
NAME=Warning_light
TOGGLE_VISIBILITY = 1
BIND_TO_HEADLIGHTS=1
COLOR=2,20,2, 1
LAG=0.2
SIMULATE_HEATING=0
LOCATION=NONE
CAST_LIGHT=0
CLUSTER_THRESHOLD=0